### ISSUE TITLE
proposed gui support

### ISSUE THREAD

**Issue by 97-109-107** [mhinz/vim-janah#1]
Using [this script](https://gist.github.com/97-109-107/c111359c5792e14ab8e8) I made your colorscheme support gvim. However, in process, it lost all the pretty formatting. Would you be interested in accepting a pull request to support gvim? If yes, I will try to clean it up. 
Here's the conversion: https://gist.github.com/97-109-107/889654d595a91d7516fd

**Comment by mhinz** [comment]
This, good sir, is awesome. Thanks!
