### ISSUE TITLE
distribute with Vim?

### ISSUE THREAD

**Issue by chrisbra** [mhinz/vim-janah#4]
there is an [issue](https://github.com/vim/vim/issues/1665) open in the vim repository, to distribute more colorschemes with Vim. Would you kindly give your permission to distribute this colorscheme with Vim?

**Comment by mhinz** [comment]
Sure. :)

Do you need me to do anything?

**Comment by chrisbra** [comment]
Well, I can collect your file and send it to Bram, or you can do it. I would prefer if you can do it, since you know obviously best, when it is kind of stable enough and of course you will know when to send updated themes to Bram for inclusion. If you want to do it, mention the issue 1665 when sending it to Bram.

**Comment by mhinz** [comment]
Okay, I sent him a mail.

**Comment by mhinz** [comment]
Status: no response.
