### ISSUE TITLE
Status line seems a bit off with powerline airline-theme

### ISSUE THREAD

**Issue by caulagi** [mhinz/vim-janah#5]
The status lines seems a bit off when I use this color scheme along with a [powerline airline-theme](https://github.com/vim-airline/vim-airline-themes) . I.e. I am not able to read the text easily in the status line.

<img width="1429" alt="screen shot 2018-06-03 at 18 39 55" src="https://user-images.githubusercontent.com/222507/40888867-c11caa5a-675d-11e8-9da8-afb2d3d5b0d0.png">

Is there a recommended way to configure/use for when using airline-theme?

**Comment by mhinz** [comment]
I don't use airline, so I have no idea which highlighting group airline is using there.

You could check the output of `:hi` for any group that uses that lightgray background. Maybe `:hi Conceal`?

**Comment by caulagi** [comment]
Thanks for the suggestion. It helped me figure out what was happening. I switched to _minimalist_ which seems good to me. Airline seems to defines its own groups, so I understand it would be odd to add it to your color scheme.

<img width="683" alt="screen shot 2018-06-03 at 20 26 47" src="https://user-images.githubusercontent.com/222507/40889777-cfb64206-676c-11e8-9fda-0c10d8486663.png">
