### ISSUE TITLE
terminal mode colors?

### ISSUE THREAD

**Issue by mmlb** [mhinz/vim-janah#7]
I've been using this scheme for a while and really like it. I'd like to use it in my terminal, and have started looking to setup the terminal colors with this scheme. Do you happen to have it already?

**Comment by mhinz** [comment]
Nope, I'm not using RGB colors yet.. do you want to create a PR for it?

**Comment by mmlb** [comment]
I haven't nailed down the colors myself yet, was looking to see if you had something already. I'll be happy to PR when I get to it. :D

**Comment by mhinz** [comment]
I guess it won't happen anytime soon, so I'm closing this. :->
